### ISSUE TITLE
Ajouter un readme

### ISSUE THREAD

**Issue by mikalziane** [RedScipio/Turn-base-game-PJS5#1]
Avec les noms, pseudo github et groupes des membres du projet et ce sur quoi ils vont travailler

**Comment by Beowulf-0** [comment]
Bonjour monsieur, 
Comme prévu, un readme a été ajouté sur la branche master avec les informations demandées : https://github.com/RedScipio/Turn-base-game-PJS5/blob/master/readme_groupe_pjs5.md

N'hésitez pas à me contacter en mp sur discord s'il y a un problème avec le lien ou si le readme n'est pas disponible sur Github.
