### ISSUE TITLE
Refacto Project Robot, Consumable, Battle

### ISSUE THREAD

**Issue by RedScipio** [RedScipio/Turn-base-game-PJS5#27]

**Comment by Beowulf-0** [comment]
Actually working on Consumable, unit testing repairing / refueling value of repair / refuel kits

**Comment by RedScipio** [comment]
Ready on
https://github.com/RedScipio/Turn-base-game-PJS5/tree/Refacto-Code

**Comment by RedScipio** [comment]
Ready on
https://github.com/RedScipio/Turn-base-game-PJS5/tree/Refacto-Code
